include:
  - project: yody-system/devops/cicd-templates
    file: compile-build.yml
    ref: master
  - project: yody-system/devops/cicd-templates
    file: sonar.yml
    ref: master

default:
  image: maven:3.6.1-jdk-8

cache:
  key: $CI_PROJECT_NAMESPACE:$CI_PROJECT_NAME
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

stages:
  - compile_build
  - docker_build
  - deploy_config
  - deploy_server
  - sona_check

sornaqube check:
  extends: .sornaqube

compile deploy:
  tags:
    - build-yody-tag
  stage: deploy_server
  script:
    - mvn -s maven/settings.xml --batch-mode -U clean package deploy
  only:
    refs:
      - develop
      - uat