include:
  - project: yody-system/devops/cicd-templates
    file: before-scripts-template.yml
    ref: master

default:
  image: maven:3.6.1-jdk-8

cache:
  key: "$CI_PROJECT_NAMESPACE:$CI_PROJECT_NAME"
  paths:
    - .m2/repository

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  GIT_SUBMODULE_STRATEGY: recursive

.before_script: &before_script |
  mkdir -p $CI_PROJECT_DIR/.m2/repository

before_script:
  - *before_script

stages:
  - test
  - deploy
  - tag
  - notify
  - sona_check

sornaqube check:
  image: 610881553522.dkr.ecr.ap-southeast-1.amazonaws.com/maven:3.6.1-jdk-8
  stage: sona_check
  when: manual
  tags:
    - build-yody-tag
  before_script:
    - mkdir -p $CI_PROJECT_DIR/.m2/repository
  script:
    - mvn -s maven/settings.xml clean install sonar:sonar -Dsonar.projectKey=yody-$CI_PROJECT_NAME -Dsonar.host.url=https://sonarqube.yody.io -Dsonar.login=$SONA_TOKEN
  only:
    - develop

compile deploy:
  tags:
    - build-yody-tag
  stage: deploy
  script:
    - mvn -s maven/settings.xml --batch-mode -U clean package deploy
  only:
    refs:
      - develop
      - uat
      - feature/refactor-config

tag:
  stage: tag
  when: manual
  only:
    - tags
  script:
    - mvn -s maven/settings.xml --batch-mode clean package deploy
