package com.yody.common.enums;

public enum ProductEventEnum {
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,
  CREATE_VARIANT,
  UPDATE_VARIANT,
  DELETE_VARIANT,
  ADD_VARIANT_PRICE,
  DELETE_VARIANT_PRICE,
  UPDATE_VARIANT_IMAGE,
  CREATE_VARIANT_IMAGE,
  UPDATE_VARIANT_PRICE,
}
